name: ${project.name}
version: ${project.version}
description: ${project.description}
authors: [Wietje, andypandy89]
main: ${project.groupId}.${project.artifactId}.${project.name}
depend: [WorldEdit, Vault]
softdepend: [Essentials, WhatIsIt, CommandHelper, Multiverse-Core, WorldGuard]

commands:
  skywars:
    aliases: [sw]
    description: Main command of the SkyWars plugin
  global:
    aliases: [g]
    description: Allows you to send a message to all players